### ISSUE TITLE
Find my pathway

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#152]
**Description of new feature**

When a user does their experiment, they're probably interested in a few pathways (~1-3).

Requirements:

- It should be easy to find a pathway in the result.
- If I'm interested in a pathway, it should not be filtered out by the algorithm.

**Motivation for new feature**

If I'm interested in knowing about particular pathways, the app doesn't give me much if I can't find them.

**Comment by mikekucera** [comment]
I'm a bit worried about the idea of having the user input the pathways up front...
- What if they make a typo? Do they have to re-run the analysis to fix it?
- What if the text they enter matches several pathways (there are tons of similar pathways in the DB, which is why we collapse them)
- We are forcing them to think about something up front, which may be a deterrent for someone who just wants to try out the app to see if they like it.
- What if they are interested in 2-3 pathways, do they have to input all of them up front? What if they forget about one of them, do they have to re-run the anaysis?

I'm think that some kind of search feature that lets them add the pathways to the figure after the fact will be more robust.
