### ISSUE TITLE
Tapping the network background should clear the highlight

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#227]
**Describe the bug**
_A clear and concise description of what the bug is._

When you're using an iPad, you can tap a gene name to highlight the network.  When you tap in the network, like the background, it doesn't reset.

**To Reproduce**
1. Go to the demo network
2. Tap on a gene in the panel
3. Tap the network background

**Expected behavior**
_A clear and concise description of what you expected to happen._

The highlight should be cleared on tap of the background, possibly by tapping other things like nodes too.

**Comment by chrtannus** [comment]
The problem is that iOS and Android uses the`:hover` selector for single-finger tap events and, in order to trigger a **mouse-leave** event on the tapped element, you have to tap another HTML element. However tapping the Cytoscape canvas does not trigger such events.
Notice that the same issue happens on the Pathways table, when tapping a row. Tap and drag a row to prevent a selection and the hover style is applied to the row. You then have to tap another HTML element to clear the row's hover style, but tapping Cytoscape doesn't do that.

I don't know if it's easy or even makes sense to trigger a mouse-leave event programatically in React (in this case, from a Cytoscape 'tap' event).
I could remove the `:hover` selector and use a React state to set the style programatically. Actually, I just tried exactly that (with a listener for Cytoscape 'tap' events):

```cyEmitter.on('tap', () => updateCyHighlights());```

That works, but the hovering effect on the gene entry becomes much slower than with the CSS `:hover`, and this also makes the issue #221 (_Hover effect on genes gets stuck_) a lot more frequent (probably because the use of React state re-renders the gene list component, which prevents `onMouseLeave` on the original element from being called):

![emweb-bug-221](https://github.com/cytoscape/enrichment-map-webapp/assets/989686/9ebd560a-5a28-4816-a01d-40582fb490c0)

So this fixes the problem on iOS and Android, but creates more problems on the desktop.
I'm wondering if we should instead replace the _hover_ action with a _click_--clicking a gene item would both expand its description/linkouts and highlight the nodes; clicking the same gene again or another element (including Cytoscape) would clear the gene selection and the node/edge highlighting.

**Comment by maxkfranz** [comment]
Good info. Do you have your current changes in a branch. Let me take a look and there’s probably a simple fix. ThanksOn Jan 24, 2024, at 14:08, Christian Lopes ***@***.***> wrote:﻿
The problem is that iOS and Android uses the:hover selector for single-finger tap events and, in order to trigger a mouse-leave event on the tapped element, you have to tap another HTML element. However tapping the Cytoscape canvas does not trigger such events.
Notice that the same issue happens on the Pathways table, when tapping a row. Tap and drag a row to prevent a selection and the hover style is applied to the row. You then have to tap another HTML element to clear the row's hover style, but tapping Cytoscape doesn't do that.
I don't know if it's easy or even makes sense to trigger a mouse-leave event programatically in React (in this case, from a Cytoscape 'tap' event).
I could remove the :hover selector and use a React state to set the style programatically. Actually, I just tried exactly that (with a listener for Cytoscape 'tap' events):
cyEmitter.on('tap', () => updateCyHighlights());
That works, but the hovering effect on the gene entry becomes much slower than with the CSS :hover, and this also makes the issue #221 (Hover effect on genes gets stuck) a lot more frequent (probably because the use of React state re-renders the gene list component, which prevents onMouseLeave on the original element from being called):
emweb-bug-221.gif (view on web)
So this fixes the problem on iOS and Android, but creates more problems on the desktop.
I'm wondering if we should instead replace the hover action with a click--clicking a gene item would both expand its description/linkouts and highlight the nodes; clicking the same gene again or another element (including Cytoscape) would clear the gene selection and the node/edge highlighting.

**Comment by maxkfranz** [comment]
As discussed today: Let's go with click.
