### ISSUE TITLE
Pathway table updates

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#270]
**Description of new feature**

- [x] Get rid of the checkboxes
- [x] Update cluster icon

<img width="766" alt="current-pathway-table" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/a3145a5a-6656-4a26-a83e-1dbe0ea7939d">
<br /><br />

- [x] Handle long pathway names better (e.g. tooltips, allow line breaks)

**Motivation for new feature**

Check boxes are confused for a filter

**Comment by chrtannus** [comment]
This is the new look (no checkboxes + updated cluster icon):

<img width="766" alt="updated-pathway-table" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/9a2e84bc-bde3-4917-8b04-79defacc893e">

**Comment by mikekucera** [comment]
Looks good. The new cluster icons are much better because they look like the clusters in the network.

**Comment by chrtannus** [comment]
This is how the pathway names look now on the **iPhone 13 Pro**, with line breaks allowed:

<img width="397" alt="pathway-linebreak-iphone13pro" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/80490448-46d4-48b8-9ff3-d699f74881b0">

I think this is more useful than trimming the text and showing tooltips, specially on touch devices.
Notice that I also increased the table height on narrow screens, otherwise the table would display only a couple of rows.
