### ISSUE TITLE
The gene list can take too long to load when there are thousands of genes

### ISSUE THREAD

**Issue by chrtannus** [cytoscape/enrichment-map-webapp#35]
**Describe the bug**
Just load the large sample network, which has 8,158 genes, and notice how the gene list usually takes several seconds to load after the cy network has been rendered.

**Comment by mikekucera** [comment]
Putting a console.time/timeEnd around the endpoint shows that it returns in about 50ms. The gene list in the browser still shows the loading animation for several seconds the endpoint returns. That suggests most of the time is being taken by something on the client.

**Comment by maxkfranz** [comment]
The PR looks great.  I think what we have is good enough for now.

I'm just going to log some items here for reference.  They might be useful for refinements in future:

- Using an overscan of 1x before and after usually works pretty well with this approach.  That way, you always have an extra screen's worth of content to scroll into.
- The issue of having black, empty space when the list is trying to update can be mitigated:  You can show a preview using a repeated background image.  This works best when the items are fixed-height, so then the image can be aligned with how the items are listed.
- If we end up needing to use a solution with a fixed height per element, we could remove the expand/collapse feature from the sidebar.  Instead, the content could be shown in a tooltip under the name when you click.  Since you don't need any of that info persistently anyway, the usual downsides of using a tooltip are mitigated.  
  - Say I want the link for a gene.  I just want to get the link, and afterwards I don't need to see the blue link anymore since I have the link open in a new tab.  In that case, it's actually better with the tooltip since it closes for me automatically when I move onto something else.
  - You probably don't need to see the description twice either.  So seeing it once and it's convenient to have the tooltip automatically close when I move on to (and click on) something else.
  - The tooltip may make user more forgiving of the loading wait time when you click to get info.  A tooltip is a separate thing, so it's more natural that it might have to load info externally.
