### ISSUE TITLE
Improving share

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/enrichment-map-webapp#51]
**Description of new feature**

- Simple menu inside share icon (like right click, just list of text menu items)
- Download image of figure
- Share by email
- Can add other options later

**Motivation for new feature**

Simplify the share menu and allow for expanding in future (e.g. export to Cytoscape).

**Comment by mikekucera** [comment]
Currently the "send by email" option uses a "mailto:" link to open the user's preferred email client. 

This approach is simple but very limited. Its not good for complex email templates that include images. And personally I hate mailto links because I couldn't be bothered to set up gmail in my mac preferences so it opens the mac mail app which I never use. I can't even remember the last time I clicked a mailto link on any website, so this seems like a very outdated approach.

In the long run we might need a server based solution. Since we don't have the user's email stored anywhere we're going to have to show a popup where the user can enter one or more email addresses. We'll need a new endpoint that accepts the addresses. Another issue is that the network image generation happens on the client, so we would have to send the image to the server somehow (base64?) and then have the server send off the email (I don't think we should use cytosnap).

Do you guys know of any better solutions?
What should we do for MVP? Simplest is to keep the "mailto:" link for now.
