### ISSUE TITLE
Gene with long name layout issue

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#53]
<img width="1131" alt="Screen Shot 2022-12-06 at 10 16 40 AM" src="https://user-images.githubusercontent.com/5350528/205951114-f4c4e610-7a61-4fbc-a26a-2a8dd724cd81.png">

**Comment by maxkfranz** [comment]
Some approaches:

- Truncate long names with an ellipsis, something like `overflow: ellipsis; max-width: 123px`.  You may need a tooltip to see the full name, and you’d have to consider how this plays with search.
- Make the bars smaller.
- Put the bars in a layer below the text.  The text may overlap the bars a bit, but probably the test would mostly overlap the black background of the bar rather than the coloured value.

**Comment by mikekucera** [comment]
Here's how it looks with Veronique's latest sample data...
<img width="1063" alt="Screen Shot 2022-12-09 at 11 08 46 AM" src="https://user-images.githubusercontent.com/5350528/206743952-bd4542df-8bdb-46ff-9786-2473aa35cb36.png">

**Comment by maxkfranz** [comment]
Let's go with this for now:

> Truncate long names with an ellipsis, something like overflow: ellipsis; max-width: 123px. You may need a tooltip to see the full name, and you’d have to consider how this plays with search.

**Comment by maxkfranz** [comment]
Closing as #65 has been merged

**Comment by chrtannus** [comment]
Regression:
<img width="317" alt="UI-long-gene-name-bug" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/a8abe6a9-9af3-410e-bbe4-34f534150fb9">

**Comment by chrtannus** [comment]
I managed to get my previous example (`GSE129943_rsem_counts_HGNC_expr.txt`) to fit the available space:
  <img width="318" alt="HGNC_expr" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/bd91496b-6397-453a-9257-332f22ebdd46">

But longer names (e.g. `RP13-1056D16.2`) should now show the ellipsis:
    <img width="320" alt="RP13-1056D16 2" src="https://github.com/cytoscape/enrichment-map-webapp/assets/989686/c52b0596-632b-4fcd-a8df-4401128a259f">
