### ISSUE TITLE
Node info popover

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/enrichment-map-webapp#88]
**Description of new feature**

Remove the pathway accordion from the left panel.  Replace with a popover that shows when clicking (or hovering?) a node. The popover may include the following information.
- The full node label
- The NES/p-value score
- The names of the pathways associated with the node (with linkouts).

**Motivation for new feature**

- Allows this info to be seen even when the left panel is collapsed.
- Better use of screen space (maybe?). Reduces the amount of information we are cramming into the left panel.
- Makes it more obvious to the user (they may not notice the accordion expanding in the left panel).
- Makes network more interactive.

**Comment by maxkfranz** [comment]
@mikekucera @chrtannus, I can start this off and hook up tooltips to the graph, but we'll still need to design exactly what goes in the tooltips.

Once the empty tooltips are there, you're welcome to fill in the content if you're interested in that.

**Comment by mikekucera** [comment]
I assume by "dot" you mean something like this: https://mui.com/material-ui/react-badge/, 

I'm hesitant to show genes in the popover, I think it will me messy and inconsistent since we already have a panel for showing genes. (I agree we could automaticaly show or flash the sidebar). The issue is that a node represents the union of all the genes in the pathways that have been collapsed to that node. If the user wants to see just the genes for a single pathway how would we show that? The sidebar would need to make it clear that its showing the genes for one pathway and not a union of pathways. Perhaps a label at the top would be sufficient.

**Comment by maxkfranz** [comment]
The node title summarises the GO terms pretty well.  The reason those GO terms are merged into one node is because the gene sets overlap so much anyway.  So it’s probably not that interesting to see the particular genes in one GO term versus another GO term within one node.

So it may be enough to do one option, like one of the following:

(1) Just show the list of links, but don’t communicate them as ‘sub-pathways’ or ‘pathways within this node’.  They’re just associated pathway links, or GO links.

(2) Only show one link.  GO is an ontology.  If you have one pathway / GO annotation, show it’s one links.  If you have more than one, then use a link for the GO term that’s the common ancestor of the set.

(3) Don’t bother listing the sub-pathway links at all.  The summarised label might be enough.  Either link to the top-level GO term, or maybe there’s a way to link to multiple GO terms in one link (e.g. with a highlighted tree of the query terms).

**Comment by maxkfranz** [comment]
If you do a search, you can get multiple results in one view using the basket: https://www.ebi.ac.uk/QuickGO/search/endogenous%20stimulus%20cellular%20response%20organic

There may be a way to link to this directly with their API.

![Comparison chart for GO_0071310,GO_0009719,GO_0071495](https://user-images.githubusercontent.com/989043/229578387-0bd7ee19-22fe-4bae-aa7d-3080391c98b5.png)

**Comment by mikekucera** [comment]
We can treat a node like its "one thing". Meaning we show one average NES value, one p-value, one size, one list of genes, etc. Or we can treat it like its a "set of things", and show the individual pathways, NES values for each pathway etc... 

I feel like "one thing" will be much cleaner. We will be showing the user less data, therefore less clutter. And we don't have to worry too much about nodes that have a single pathway being a special case. If we could have a single linkout for the entire node that would make it very simple on our end. I'm not sure if that's what users want though.

**Comment by maxkfranz** [comment]
Re. one thing v.s. set of things:  Right now, we have the worst of all worlds.  We display the nodes as one thing, and then we display the data for the node as a set of things.  This probably contributed to the confusion around the pathways panel.

We should do one thing or the other.  A mix is mixed messaging.  It's one node that's displayed as one thing in the upcoming tooltip; or it's a compound node with a set of child nodes, each with their own tooltip.

> I'm not sure if that's what users want though.

For what it's worth, no one clicked the linkouts for pathways.  People focussed on the node labels.

Looking back, I'm not sure why we assumed that people needed pathway links.  Maybe the desktop has it?  A lot of the information in links like QuickGO look interesting only to people like curators...

If we don't need a pathway list with links, the only things left are things like p-value and NES.  All nodes have a good p-value, or why would we show them?  And you can already see the most important part of NES by the colour dichotomy at a glance (up/down).  The genes are definitely the most important thing when you click a node.

What if we start with the simplest thing?  No tooltip.  Clicking a node just opens the genes sidebar, if closed.  We could test that with users and see if we really need to add anything more.

**Comment by mikekucera** [comment]
We could show the node's NES value as a marker on the legend, like this...
I mocked that up very quickly so imagine it looks more obvious.

<img width="1070" alt="Screenshot 2023-04-03 at 7 19 11 PM" src="https://user-images.githubusercontent.com/5350528/229647473-11603bc8-dae9-403c-997a-91f81ff52189.png">

**Comment by maxkfranz** [comment]
I’ve logged the tasks:

- #99 
- #101 
- #100 

I’ve marked the legend indicator as future / medium, because it seems less definite than the others, but feel free to bump it up if you think it’s more important or you just have the time.

Is there anything else to discuss for this issue?  If we’re not doing the tooltips and the other issues suffice, then we can close this.
